### ISSUE TITLE
Error when loading plugin

### ISSUE THREAD

**Issue by sdy12318** [DirtyRacer1337/Emby.Plugins.PhoenixAdult#2]
I put Flurl.Http.dll, HtmlAgilityPack.dll, Flurl.dll, Newtonsoft.Json.dll, Emby.Plugins.PhoenixAdult.dll, PhoenixAdult.NET.dll inside EmbyServer/programdata/plugins/.

After restarting Emby, the log shows:
Error App: LoaderException: 'PhoenixAdult.NET, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null'. Could not load file or assembly. The system cannot find the file specified.
Error App: LoaderException: Could not load file or assembly 'HtmlAgilityPack, Version=1.11.24.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a'. The system cannot find the file specified.
Error App: LoaderException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

[log.txt](https://github.com/DirtyRacer1337/Emby.Plugins.PhoenixAdult/files/4957850/log.txt)

**Comment by DirtyRacer1337** [comment]
Everythin you need already inside of `Emby.Plugins.PhoenixAdult.dll`

**Comment by sdy12318** [comment]
The log still shows 

`Error App: LoaderException: Could not load file or assembly 'PhoenixAdult.NET, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

after I put Emby.Plugins.PhoenixAdult.dll inside plugins folder.

**Comment by DirtyRacer1337** [comment]
`PhoenixAdult.NET.dll` not required too

**Comment by sdy12318** [comment]
I put `PhoenixAdult.NET.dll` and `Emby.Plugins.PhoenixAdult.dll`, getting more error:
`Error App: LoaderException: Could not load file or assembly 'PhoenixAdult.NET, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`
`Error App: LoaderException: Could not load file or assembly 'HtmlAgilityPack, Version=1.11.24.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a'. The system cannot find the file specified.`
`Error App: LoaderException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.`
[log.txt](https://github.com/DirtyRacer1337/Emby.Plugins.PhoenixAdult/files/4961544/log.txt)

**Comment by DirtyRacer1337** [comment]
You nedd only `Emby.Plugins.PhoenixAdult.dll`

**Comment by sdy12318** [comment]
I tried only to put `Emby.Plugins.PhoenixAdult.dll` inside plugins folder, getting this error:

`Error App: LoaderException: Could not load file or assembly 'PhoenixAdult.NET, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

**Comment by DirtyRacer1337** [comment]
That log mean you not deleted it, then just ignore it should works anyway

**Comment by sdy12318** [comment]
I figured it out. I use the wrong `Emby.Plugins.PhoenixAdult.dl` file. The bin folder is outside the `Emby.Plugins.PhoenixAdult` folder. I switched to the file inside `Emby.Plugins.PhoenixAdult-master\Emby.Plugins.PhoenixAdult\bin\Release\netstandard2.0` and it works. Thanks!

**Comment by DirtyRacer1337** [comment]
I think you forgot to tell me, you not use version from releases and build it
